<?php

namespace DoctrineORMModule\Proxy\__CG__\CsnUser\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Estudios extends \CsnUser\Entity\Estudios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'ID', 'PACIENTE', 'FECHA', 'PACIENTE_NR', 'TIPOS', 'DOCTOR', 'ESTADO', 'USUARIO', 'DOCTORENV', 'EVENTO', 'REVISION', 'INTERPRETACION', 'PAGADO', 'PDFTOKEN', 'FOLIORECETA', 'FECHARECETA', 'DEPENDENCIA', 'RECEPTOR');
        }

        return array('__isInitialized__', 'ID', 'PACIENTE', 'FECHA', 'PACIENTE_NR', 'TIPOS', 'DOCTOR', 'ESTADO', 'USUARIO', 'DOCTORENV', 'EVENTO', 'REVISION', 'INTERPRETACION', 'PAGADO', 'PDFTOKEN', 'FOLIORECETA', 'FECHARECETA', 'DEPENDENCIA', 'RECEPTOR');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Estudios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', array());

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function setID($ID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setID', array($ID));

        return parent::setID($ID);
    }

    /**
     * {@inheritDoc}
     */
    public function getPACIENTE()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPACIENTE', array());

        return parent::getPACIENTE();
    }

    /**
     * {@inheritDoc}
     */
    public function getEVENTO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEVENTO', array());

        return parent::getEVENTO();
    }

    /**
     * {@inheritDoc}
     */
    public function setEVENTO($EVENTO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEVENTO', array($EVENTO));

        return parent::setEVENTO($EVENTO);
    }

    /**
     * {@inheritDoc}
     */
    public function setPACIENTE($PACIENTE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPACIENTE', array($PACIENTE));

        return parent::setPACIENTE($PACIENTE);
    }

    /**
     * {@inheritDoc}
     */
    public function getFECHA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFECHA', array());

        return parent::getFECHA();
    }

    /**
     * {@inheritDoc}
     */
    public function setFECHA($FECHA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFECHA', array($FECHA));

        return parent::setFECHA($FECHA);
    }

    /**
     * {@inheritDoc}
     */
    public function getTIPOS()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTIPOS', array());

        return parent::getTIPOS();
    }

    /**
     * {@inheritDoc}
     */
    public function addTIPOS(\Doctrine\Common\Collections\Collection $TIPOS)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTIPOS', array($TIPOS));

        return parent::addTIPOS($TIPOS);
    }

    /**
     * {@inheritDoc}
     */
    public function addTIPO(\CsnUser\Entity\Tiposestudio $CATEGORIA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTIPO', array($CATEGORIA));

        return parent::addTIPO($CATEGORIA);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTIPO(\CsnUser\Entity\Tiposestudio $CATEGORIA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTIPO', array($CATEGORIA));

        return parent::removeTIPO($CATEGORIA);
    }

    /**
     * {@inheritDoc}
     */
    public function getDOCTOR()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDOCTOR', array());

        return parent::getDOCTOR();
    }

    /**
     * {@inheritDoc}
     */
    public function setDOCTOR($DOCTOR)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDOCTOR', array($DOCTOR));

        return parent::setDOCTOR($DOCTOR);
    }

    /**
     * {@inheritDoc}
     */
    public function getESTADO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getESTADO', array());

        return parent::getESTADO();
    }

    /**
     * {@inheritDoc}
     */
    public function setESTADO($ESTADO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setESTADO', array($ESTADO));

        return parent::setESTADO($ESTADO);
    }

    /**
     * {@inheritDoc}
     */
    public function getUSUARIO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUSUARIO', array());

        return parent::getUSUARIO();
    }

    /**
     * {@inheritDoc}
     */
    public function setUSUARIO($USUARIO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUSUARIO', array($USUARIO));

        return parent::setUSUARIO($USUARIO);
    }

    /**
     * {@inheritDoc}
     */
    public function getDOCTORENV()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDOCTORENV', array());

        return parent::getDOCTORENV();
    }

    /**
     * {@inheritDoc}
     */
    public function setDOCTORENV($DOCTORENV)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDOCTORENV', array($DOCTORENV));

        return parent::setDOCTORENV($DOCTORENV);
    }

    /**
     * {@inheritDoc}
     */
    public function getINTERPRETACION()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getINTERPRETACION', array());

        return parent::getINTERPRETACION();
    }

    /**
     * {@inheritDoc}
     */
    public function setINTERPRETACION($INTERPRETACION)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setINTERPRETACION', array($INTERPRETACION));

        return parent::setINTERPRETACION($INTERPRETACION);
    }

    /**
     * {@inheritDoc}
     */
    public function getREVISION()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getREVISION', array());

        return parent::getREVISION();
    }

    /**
     * {@inheritDoc}
     */
    public function setREVISION($REVISION)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setREVISION', array($REVISION));

        return parent::setREVISION($REVISION);
    }

    /**
     * {@inheritDoc}
     */
    public function getPDFTOKEN()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPDFTOKEN', array());

        return parent::getPDFTOKEN();
    }

    /**
     * {@inheritDoc}
     */
    public function setPDFTOKEN($PDFTOKEN)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPDFTOKEN', array($PDFTOKEN));

        return parent::setPDFTOKEN($PDFTOKEN);
    }

    /**
     * {@inheritDoc}
     */
    public function getPACIENTENR()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPACIENTENR', array());

        return parent::getPACIENTENR();
    }

    /**
     * {@inheritDoc}
     */
    public function setPACIENTENR($PACIENTE_NR)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPACIENTENR', array($PACIENTE_NR));

        return parent::setPACIENTENR($PACIENTE_NR);
    }

    /**
     * {@inheritDoc}
     */
    public function getFOLIORECETA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFOLIORECETA', array());

        return parent::getFOLIORECETA();
    }

    /**
     * {@inheritDoc}
     */
    public function setFOLIORECETA($FOLIORECETA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFOLIORECETA', array($FOLIORECETA));

        return parent::setFOLIORECETA($FOLIORECETA);
    }

    /**
     * {@inheritDoc}
     */
    public function getFECHARECETA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFECHARECETA', array());

        return parent::getFECHARECETA();
    }

    /**
     * {@inheritDoc}
     */
    public function setFECHARECETA($FECHARECETA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFECHARECETA', array($FECHARECETA));

        return parent::setFECHARECETA($FECHARECETA);
    }

    /**
     * {@inheritDoc}
     */
    public function getDEPENDENCIA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDEPENDENCIA', array());

        return parent::getDEPENDENCIA();
    }

    /**
     * {@inheritDoc}
     */
    public function setDEPENDENCIA($DEPENDENCIA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDEPENDENCIA', array($DEPENDENCIA));

        return parent::setDEPENDENCIA($DEPENDENCIA);
    }

    /**
     * {@inheritDoc}
     */
    public function getRECEPTOR()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRECEPTOR', array());

        return parent::getRECEPTOR();
    }

    /**
     * {@inheritDoc}
     */
    public function setRECEPTOR($RECEPTOR)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRECEPTOR', array($RECEPTOR));

        return parent::setRECEPTOR($RECEPTOR);
    }

    /**
     * {@inheritDoc}
     */
    public function getPAGADO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPAGADO', array());

        return parent::getPAGADO();
    }

    /**
     * {@inheritDoc}
     */
    public function setPAGADO($PAGADO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPAGADO', array($PAGADO));

        return parent::setPAGADO($PAGADO);
    }

}
