<?php

namespace DoctrineORMModule\Proxy\__CG__\CsnUser\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pacientes extends \CsnUser\Entity\Pacientes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'ID', 'CURP', 'SEXO', 'NOMBRE', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'FECHA_NACIMIENTO', 'NIVEL_SOCIOECONOMICO', 'OCUPACION', 'EMBARAZO', 'TIPO_SANGUINEO', 'DISCAPACIDAD', 'GRUPO_ETNICO', 'ESTADO', 'MUNICIPIO', 'CALLE', 'NUMERO_EXT', 'NUMERO_INT', 'VIVIENDA', 'CODIGO_POSTAL', 'COLONIA', 'TELEFONO_1', 'TELEFONO_2', 'EMAIL', 'RFC', 'CLIENTE', 'FECHA_REGISTRO', 'AFILIACION', 'ANTECEDENTES');
        }

        return array('__isInitialized__', 'ID', 'CURP', 'SEXO', 'NOMBRE', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'FECHA_NACIMIENTO', 'NIVEL_SOCIOECONOMICO', 'OCUPACION', 'EMBARAZO', 'TIPO_SANGUINEO', 'DISCAPACIDAD', 'GRUPO_ETNICO', 'ESTADO', 'MUNICIPIO', 'CALLE', 'NUMERO_EXT', 'NUMERO_INT', 'VIVIENDA', 'CODIGO_POSTAL', 'COLONIA', 'TELEFONO_1', 'TELEFONO_2', 'EMAIL', 'RFC', 'CLIENTE', 'FECHA_REGISTRO', 'AFILIACION', 'ANTECEDENTES');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pacientes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', array());

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function setID($ID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setID', array($ID));

        return parent::setID($ID);
    }

    /**
     * {@inheritDoc}
     */
    public function getCURP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCURP', array());

        return parent::getCURP();
    }

    /**
     * {@inheritDoc}
     */
    public function setCURP($CURP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCURP', array($CURP));

        return parent::setCURP($CURP);
    }

    /**
     * {@inheritDoc}
     */
    public function getNOMBRE()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNOMBRE', array());

        return parent::getNOMBRE();
    }

    /**
     * {@inheritDoc}
     */
    public function setNOMBRE($NOMBRE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNOMBRE', array($NOMBRE));

        return parent::setNOMBRE($NOMBRE);
    }

    /**
     * {@inheritDoc}
     */
    public function getAPELLIDO_PATERNO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAPELLIDO_PATERNO', array());

        return parent::getAPELLIDO_PATERNO();
    }

    /**
     * {@inheritDoc}
     */
    public function setAPELLIDO_PATERNO($APELLIDO_PATERNO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAPELLIDO_PATERNO', array($APELLIDO_PATERNO));

        return parent::setAPELLIDO_PATERNO($APELLIDO_PATERNO);
    }

    /**
     * {@inheritDoc}
     */
    public function getAPELLIDO_MATERNO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAPELLIDO_MATERNO', array());

        return parent::getAPELLIDO_MATERNO();
    }

    /**
     * {@inheritDoc}
     */
    public function setAPELLIDO_MATERNO($APELLIDO_MATERNO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAPELLIDO_MATERNO', array($APELLIDO_MATERNO));

        return parent::setAPELLIDO_MATERNO($APELLIDO_MATERNO);
    }

    /**
     * {@inheritDoc}
     */
    public function getNIVEL_SOCIOECONOMICO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNIVEL_SOCIOECONOMICO', array());

        return parent::getNIVEL_SOCIOECONOMICO();
    }

    /**
     * {@inheritDoc}
     */
    public function setNIVEL_SOCIOECONOMICO($NIVEL_SOCIOECONOMICO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNIVEL_SOCIOECONOMICO', array($NIVEL_SOCIOECONOMICO));

        return parent::setNIVEL_SOCIOECONOMICO($NIVEL_SOCIOECONOMICO);
    }

    /**
     * {@inheritDoc}
     */
    public function getTIPO_SANGUINEO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTIPO_SANGUINEO', array());

        return parent::getTIPO_SANGUINEO();
    }

    /**
     * {@inheritDoc}
     */
    public function setTIPO_SANGUINEO($TIPO_SANGUINEO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTIPO_SANGUINEO', array($TIPO_SANGUINEO));

        return parent::setTIPO_SANGUINEO($TIPO_SANGUINEO);
    }

    /**
     * {@inheritDoc}
     */
    public function getDISCAPACIDAD()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDISCAPACIDAD', array());

        return parent::getDISCAPACIDAD();
    }

    /**
     * {@inheritDoc}
     */
    public function setDISCAPACIDAD($DISCAPACIDAD)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDISCAPACIDAD', array($DISCAPACIDAD));

        return parent::setDISCAPACIDAD($DISCAPACIDAD);
    }

    /**
     * {@inheritDoc}
     */
    public function getGRUPO_ETNICO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGRUPO_ETNICO', array());

        return parent::getGRUPO_ETNICO();
    }

    /**
     * {@inheritDoc}
     */
    public function setGRUPO_ETNICO($GRUPO_ETNICO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGRUPO_ETNICO', array($GRUPO_ETNICO));

        return parent::setGRUPO_ETNICO($GRUPO_ETNICO);
    }

    /**
     * {@inheritDoc}
     */
    public function getESTADO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getESTADO', array());

        return parent::getESTADO();
    }

    /**
     * {@inheritDoc}
     */
    public function setESTADO($ESTADO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setESTADO', array($ESTADO));

        return parent::setESTADO($ESTADO);
    }

    /**
     * {@inheritDoc}
     */
    public function getMUNICIPIO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMUNICIPIO', array());

        return parent::getMUNICIPIO();
    }

    /**
     * {@inheritDoc}
     */
    public function setMUNICIPIO($MUNICIPIO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMUNICIPIO', array($MUNICIPIO));

        return parent::setMUNICIPIO($MUNICIPIO);
    }

    /**
     * {@inheritDoc}
     */
    public function getCALLE()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCALLE', array());

        return parent::getCALLE();
    }

    /**
     * {@inheritDoc}
     */
    public function setCALLE($CALLE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCALLE', array($CALLE));

        return parent::setCALLE($CALLE);
    }

    /**
     * {@inheritDoc}
     */
    public function getNUMERO_EXT()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNUMERO_EXT', array());

        return parent::getNUMERO_EXT();
    }

    /**
     * {@inheritDoc}
     */
    public function setNUMERO_EXT($NUMERO_EXT)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNUMERO_EXT', array($NUMERO_EXT));

        return parent::setNUMERO_EXT($NUMERO_EXT);
    }

    /**
     * {@inheritDoc}
     */
    public function getNUMERO_INT()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNUMERO_INT', array());

        return parent::getNUMERO_INT();
    }

    /**
     * {@inheritDoc}
     */
    public function setNUMERO_INT($NUMERO_INT)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNUMERO_INT', array($NUMERO_INT));

        return parent::setNUMERO_INT($NUMERO_INT);
    }

    /**
     * {@inheritDoc}
     */
    public function getVIVIENDA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVIVIENDA', array());

        return parent::getVIVIENDA();
    }

    /**
     * {@inheritDoc}
     */
    public function setVIVIENDA($VIVIENDA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVIVIENDA', array($VIVIENDA));

        return parent::setVIVIENDA($VIVIENDA);
    }

    /**
     * {@inheritDoc}
     */
    public function getCODIGO_POSTAL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCODIGO_POSTAL', array());

        return parent::getCODIGO_POSTAL();
    }

    /**
     * {@inheritDoc}
     */
    public function setCODIGO_POSTAL($CODIGO_POSTAL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCODIGO_POSTAL', array($CODIGO_POSTAL));

        return parent::setCODIGO_POSTAL($CODIGO_POSTAL);
    }

    /**
     * {@inheritDoc}
     */
    public function getCOLONIA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCOLONIA', array());

        return parent::getCOLONIA();
    }

    /**
     * {@inheritDoc}
     */
    public function setCOLONIA($COLONIA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCOLONIA', array($COLONIA));

        return parent::setCOLONIA($COLONIA);
    }

    /**
     * {@inheritDoc}
     */
    public function getTELEFONO_1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTELEFONO_1', array());

        return parent::getTELEFONO_1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTELEFONO_1($TELEFONO_1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTELEFONO_1', array($TELEFONO_1));

        return parent::setTELEFONO_1($TELEFONO_1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTELEFONO_2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTELEFONO_2', array());

        return parent::getTELEFONO_2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTELEFONO_2($TELEFONO_2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTELEFONO_2', array($TELEFONO_2));

        return parent::setTELEFONO_2($TELEFONO_2);
    }

    /**
     * {@inheritDoc}
     */
    public function getANTECEDENTES()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getANTECEDENTES', array());

        return parent::getANTECEDENTES();
    }

    /**
     * {@inheritDoc}
     */
    public function addANTECEDENTE(\CsnUser\Entity\CIE10 $CIE10)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addANTECEDENTE', array($CIE10));

        return parent::addANTECEDENTE($CIE10);
    }

    /**
     * {@inheritDoc}
     */
    public function getFECHA_REGISTRO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFECHA_REGISTRO', array());

        return parent::getFECHA_REGISTRO();
    }

    /**
     * {@inheritDoc}
     */
    public function setFECHA_REGISTRO($FECHA_REGISTRO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFECHA_REGISTRO', array($FECHA_REGISTRO));

        return parent::setFECHA_REGISTRO($FECHA_REGISTRO);
    }

    /**
     * {@inheritDoc}
     */
    public function getFECHA_NACIMIENTO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFECHA_NACIMIENTO', array());

        return parent::getFECHA_NACIMIENTO();
    }

    /**
     * {@inheritDoc}
     */
    public function setFECHA_NACIMIENTO($FECHA_NACIMIENTO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFECHA_NACIMIENTO', array($FECHA_NACIMIENTO));

        return parent::setFECHA_NACIMIENTO($FECHA_NACIMIENTO);
    }

    /**
     * {@inheritDoc}
     */
    public function getEMAIL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEMAIL', array());

        return parent::getEMAIL();
    }

    /**
     * {@inheritDoc}
     */
    public function setEMAIL($EMAIL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEMAIL', array($EMAIL));

        return parent::setEMAIL($EMAIL);
    }

    /**
     * {@inheritDoc}
     */
    public function getSEXO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSEXO', array());

        return parent::getSEXO();
    }

    /**
     * {@inheritDoc}
     */
    public function setSEXO($SEXO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSEXO', array($SEXO));

        return parent::setSEXO($SEXO);
    }

    /**
     * {@inheritDoc}
     */
    public function getOCUPACION()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOCUPACION', array());

        return parent::getOCUPACION();
    }

    /**
     * {@inheritDoc}
     */
    public function setOCUPACION($OCUPACION)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOCUPACION', array($OCUPACION));

        return parent::setOCUPACION($OCUPACION);
    }

    /**
     * {@inheritDoc}
     */
    public function getEMBARAZO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEMBARAZO', array());

        return parent::getEMBARAZO();
    }

    /**
     * {@inheritDoc}
     */
    public function setEMBARAZO($EMBARAZO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEMBARAZO', array($EMBARAZO));

        return parent::setEMBARAZO($EMBARAZO);
    }

    /**
     * {@inheritDoc}
     */
    public function getRFC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRFC', array());

        return parent::getRFC();
    }

    /**
     * {@inheritDoc}
     */
    public function setRFC($RFC)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRFC', array($RFC));

        return parent::setRFC($RFC);
    }

    /**
     * {@inheritDoc}
     */
    public function getCLIENTE()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCLIENTE', array());

        return parent::getCLIENTE();
    }

    /**
     * {@inheritDoc}
     */
    public function setCLIENTE($CLIENTE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCLIENTE', array($CLIENTE));

        return parent::setCLIENTE($CLIENTE);
    }

}
