<?php

namespace DoctrineORMModule\Proxy\__CG__\CsnUser\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agendas extends \CsnUser\Entity\Agendas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'usuariox', 'paciente', 'descripcion', 'edad', 'refdoctor', 'dependencia', 'tipo', 'telefono1', 'telefono2', 'ESTUDIO', 'title', 'allDay', 'start', 'end', 'url', 'className', 'color', 'editable', 'startEditable', 'durationEditable', 'source', 'backgroundColor', 'textColor', 'borderColor', 'country', 'doctor');
        }

        return array('__isInitialized__', 'id', 'usuariox', 'paciente', 'descripcion', 'edad', 'refdoctor', 'dependencia', 'tipo', 'telefono1', 'telefono2', 'ESTUDIO', 'title', 'allDay', 'start', 'end', 'url', 'className', 'color', 'editable', 'startEditable', 'durationEditable', 'source', 'backgroundColor', 'textColor', 'borderColor', 'country', 'doctor');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Agendas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuariox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuariox', array());

        return parent::getUsuariox();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuariox($usuariox)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuariox', array($usuariox));

        return parent::setUsuariox($usuariox);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaciente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaciente', array());

        return parent::getPaciente();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaciente($paciente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaciente', array($paciente));

        return parent::setPaciente($paciente);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllDay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllDay', array());

        return parent::getAllDay();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllDay($allDay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllDay', array($allDay));

        return parent::setAllDay($allDay);
    }

    /**
     * {@inheritDoc}
     */
    public function getStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStart', array());

        return parent::getStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setStart($start)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStart', array($start));

        return parent::setStart($start);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnd', array());

        return parent::getEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnd($end)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnd', array($end));

        return parent::setEnd($end);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassName', array());

        return parent::getClassName();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassName($className)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassName', array($className));

        return parent::setClassName($className);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', array());

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', array($color));

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditable', array());

        return parent::getEditable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditable($editable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditable', array($editable));

        return parent::setEditable($editable);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartEditable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartEditable', array());

        return parent::getStartEditable();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartEditable($startEditable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartEditable', array($startEditable));

        return parent::setStartEditable($startEditable);
    }

    /**
     * {@inheritDoc}
     */
    public function getDurationEditable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDurationEditable', array());

        return parent::getDurationEditable();
    }

    /**
     * {@inheritDoc}
     */
    public function setDurationEditable($durationEditable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDurationEditable', array($durationEditable));

        return parent::setDurationEditable($durationEditable);
    }

    /**
     * {@inheritDoc}
     */
    public function getSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', array());

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setSource($source)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', array($source));

        return parent::setSource($source);
    }

    /**
     * {@inheritDoc}
     */
    public function getBackgroundColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackgroundColor', array());

        return parent::getBackgroundColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundColor($backgroundColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundColor', array($backgroundColor));

        return parent::setBackgroundColor($backgroundColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextColor', array());

        return parent::getTextColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextColor($textColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextColor', array($textColor));

        return parent::setTextColor($textColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getBorderColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBorderColor', array());

        return parent::getBorderColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setBorderColor($borderColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBorderColor', array($borderColor));

        return parent::setBorderColor($borderColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdad', array());

        return parent::getEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdad($edad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdad', array($edad));

        return parent::setEdad($edad);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefdoctor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefdoctor', array());

        return parent::getRefdoctor();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefdoctor($refdoctor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefdoctor', array($refdoctor));

        return parent::setRefdoctor($refdoctor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDependencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependencia', array());

        return parent::getDependencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDependencia($dependencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDependencia', array($dependencia));

        return parent::setDependencia($dependencia);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipos));

        return parent::setTipo($tipos);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getDoctor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoctor', array());

        return parent::getDoctor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoctor($doctor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoctor', array($doctor));

        return parent::setDoctor($doctor);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getESTUDIO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getESTUDIO', array());

        return parent::getESTUDIO();
    }

    /**
     * {@inheritDoc}
     */
    public function setESTUDIO($ESTUDIO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setESTUDIO', array($ESTUDIO));

        return parent::setESTUDIO($ESTUDIO);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono1', array());

        return parent::getTelefono1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono1($telefono1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono1', array($telefono1));

        return parent::setTelefono1($telefono1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono2', array());

        return parent::getTelefono2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono2($telefono2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono2', array($telefono2));

        return parent::setTelefono2($telefono2);
    }

}
